# Generated by Django 2.2 on 2021-03-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_remove_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nationality',
        ),
    ]
